spring.application.name=demo
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_is_2026
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

app.evidencias.directorio=${EVIDENCIAS_DIR:./datos/evidencias}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB

spring.jpa.hibernate.ddl-auto=update